// src/components/common/TopBar.tsx
import Image from "next/image"
import Link from "next/link"
import { wrapn } from "wrapn"
import L2Logo from '../../../public/favicon.ico'
import { IconTheme } from "../icons"
import { IconBalance } from "../icons/IconBalance"
import { IconHome } from "../icons/IconHome"
import { IconNewsletter } from "../icons/IconNewsletter"
import { IconStats } from "../icons/IconStats"

export const TopBar = () => (
        <Header>
            <Link href='/' passHref>
                <Logo>
                    <Image alt='L2 Planet logo' src={L2Logo} height='32' width='32'/>
                    L2 Planet
                </Logo>
            </Link>
            <Nav>
                <Link href='/' passHref>
                    <A><IconHome/></A>
                </Link>
                <Link href='/newsletter' passHref>
                    <A><IconNewsletter/></A>
                </Link>
                <Link href='/stats' passHref>
                    <A><IconStats/></A>
                </Link>
                <Link href='/' passHref>
                    <A><IconBalance/></A>
                </Link>
            </Nav>
            <ButtonsDiv>
                <Button onClick={() => document.getElementsByTagName('html')[0].classList.toggle('dark')}>
                    <IconTheme/>
                </Button>
            </ButtonsDiv>
        </Header>
)


const Header = wrapn('header')`
    sticky top-0 z-30
    flex items-center justify-between
    h-16 px-3 sm:px-6
    backdrop-blur-xl
    border-b
    border-b-slate-100
    dark:border-b-slate-800
    bg-white/60
    dark:bg-slate-900/60
`

const Logo = wrapn('a')`
    flex items-center justify-between
    w-[9.5rem]
    font-extrabold
    text-2xl
`

const Nav = wrapn('nav')`
    hidden
    lg:flex
    space-x-8
`

const A = wrapn('a')`
    flex items-center
    font-semibold text-lg
    rounded-xl
    h-11 px-4 py-1
    hover:scale-105 active:scale-95
    border
    border-indigo-300
    dark:border-indigo-700
    bg-indigo-200/70 hover:bg-indigo-300/70 active:bg-indigo-200/70
    dark:bg-indigo-800/70 dark:hover:bg-indigo-700/70 dark:active:bg-indigo-800/70
    duration-200
`

const ButtonsDiv = wrapn('div')`
    flex justify-end
    w-[9.5rem]
`

const Button = wrapn('button')`
    h-12 p-1.5
    hover:scale-105 active:scale-95
    rounded-full border
    border-indigo-300
    dark:border-indigo-700
    bg-indigo-200/70 hover:bg-indigo-300/70 active:bg-indigo-200/70
    dark:bg-indigo-800/70 dark:hover:bg-indigo-700/70 dark:active:bg-indigo-800/70
    duration-200
`

// src/lib/components/TopBar.svelte
<script lang="ts">
    import IconMenu from "./icons/IconMenu.svelte";
</script>

<header class="sticky top-0 z-30 flex items-center justify-between h-16 px-7 bg-white/50 backdrop-blur-xl select-none">
    <!-- This element is like the brand logo of the website -->
    <a class="font-extrabold text-2xl w-28" href="/">L2 Planet</a>
    <nav class="hidden h-full md:flex items-center">
        <a href="/blog" class="flex items-center h-full px-6 font-medium text-lg hover:text-violet-600 hover:scale-110  duration-200">Blog</a>
        <a href="/l2 solutions" class="flex items-center h-full px-6 font-medium text-lg hover:text-violet-600 hover:scale-110 duration-200">L2 Solutions</a>
        <a href="/stats" class="flex items-center h-full px-6 font-medium text-lg hover:text-violet-600 hover:scale-110 duration-200">Stats</a>
    </nav>
    <!-- This button opens and closes the menu screen -->
    <button on:click class="md:hidden p-2 rounded-full active:bg-neutral-700/10 active:scale-90 duration-200">
        <IconMenu/> <p hidden>menu</p>
    </button>
    <!-- Only for testing -->
    <div class="hidden md:flex w-28"/>
</header>
